/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a supplier
         * @description Retrieves an active or inactive supplier by UUID.
         */
        get: operations["getSupplier"];
        /**
         * Replace supplier details
         * @description Fully replaces editable details while preserving status, ID, and creation time. Use the latest version to prevent lost updates. Requires an ADMIN access token.
         */
        put: operations["updateSupplier"];
        post?: never;
        /**
         * Permanently delete a supplier
         * @description Hard-deletes an active or inactive supplier. Prefer INACTIVE for normal removal from listings. The version prevents deletion of unseen changes. Requires an ADMIN access token.
         */
        delete: operations["deleteSupplier"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active suppliers
         * @description Searches and filters active suppliers. Filters combine with AND, while search matches name, building, or location description.
         */
        get: operations["listSuppliers"];
        put?: never;
        /**
         * Create a supplier
         * @description Creates an active or inactive supplier. Requires an ADMIN access token.
         */
        post: operations["createSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change supplier status
         * @description Activates or deactivates a supplier without resending its details. Use the latest version to prevent lost updates. Requires an ADMIN access token.
         */
        patch: operations["changeSupplierStatus"];
        trace?: never;
    };
    "/api/suppliers/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active supplier filter values
         * @description Returns distinct supplier types and buildings from active suppliers, sorted case-insensitively.
         */
        get: operations["getSupplierMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List suppliers for administration
         * @description Searches active and inactive suppliers. An optional status filter narrows the results. Requires an ADMIN access token.
         */
        get: operations["listSuppliersForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/suppliers/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get administrative supplier filter values
         * @description Returns distinct types and buildings across active and inactive suppliers. Requires an ADMIN access token.
         */
        get: operations["getAdminSupplierMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Complete replacement for a supplier's editable details */
        UpdateSupplierRequest: {
            /**
             * @description Supplier display name
             * @example Updated Campus Cafe
             */
            name: string;
            /**
             * @description Supplier category
             * @example Food/Coffee
             */
            type: string;
            /**
             * @description Campus building
             * @example COM3
             */
            building: string;
            /**
             * @description Floor label; omitted or blank clears the value
             * @example 2
             */
            floor?: string | null;
            /**
             * @description Directions; omitted or blank clears the value
             * @example Now beside the lift
             */
            locationDescription?: string | null;
            /**
             * Format: double
             * @description Latitude in decimal degrees
             * @example 1.2948
             */
            latitude: number;
            /**
             * Format: double
             * @description Longitude in decimal degrees
             * @example 103.7716
             */
            longitude: number;
            /**
             * Format: time
             * @description Local opening time; omitted clears the value
             * @example 09:00
             */
            openingTime?: string | null;
            /**
             * Format: time
             * @description Local closing time; overnight operation is valid
             * @example 20:00
             */
            closingTime?: string | null;
            /**
             * Format: uri
             * @description Absolute HTTP or HTTPS image URL; omitted or blank clears the value
             * @example https://example.com/updated-cafe.jpg
             */
            imageUrl?: string | null;
            /**
             * Format: int64
             * @description Version from the latest supplier response
             * @example 0
             */
            version: number;
        };
        /** @description Complete supplier representation */
        SupplierResponse: {
            /**
             * Format: uuid
             * @description Server-generated supplier identifier
             * @example ca9bd61f-93da-4500-9e9d-48de1bea52fa
             */
            readonly id?: string;
            /**
             * @description Supplier display name
             * @example Anna's x Soup Union
             */
            name?: string;
            /**
             * @description Supplier category
             * @example Food
             */
            type?: string;
            /**
             * @description Campus building
             * @example Central Library
             */
            building?: string;
            /**
             * @description Floor label
             * @example 1
             */
            floor?: string | null;
            /**
             * @description Directions within or near the building
             * @example Next to NUS Co-op
             */
            locationDescription?: string | null;
            /**
             * Format: double
             * @description Latitude in decimal degrees
             * @example 1.296444
             */
            latitude?: number;
            /**
             * Format: double
             * @description Longitude in decimal degrees
             * @example 103.773032
             */
            longitude?: number;
            /**
             * Format: time
             * @description Local opening time
             * @example 09:00
             */
            openingTime?: string | null;
            /**
             * Format: time
             * @description Local closing time
             * @example 18:00
             */
            closingTime?: string | null;
            /**
             * Format: uri
             * @description Absolute HTTP or HTTPS image URL
             */
            imageUrl?: string | null;
            /**
             * @description Current visibility status
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
            /**
             * Format: int64
             * @description Optimistic-lock version
             * @example 0
             */
            readonly version?: number;
            /**
             * Format: date-time
             * @description Creation timestamp in UTC
             * @example 2026-09-23T00:00:00Z
             */
            readonly createdAt?: string;
            /**
             * Format: date-time
             * @description Last-change timestamp in UTC
             * @example 2026-09-23T00:00:00Z
             */
            readonly updatedAt?: string;
        };
        /** @description Problem Details response for an invalid query or supplier ID */
        InvalidRequestProblem: {
            /** @example about:blank */
            type?: string;
            /** @example Invalid supplier query */
            title?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example Page must be a nonnegative whole number */
            detail?: string;
            /** @example /api/suppliers */
            instance?: string;
        };
        /** @description Problem Details response for an invalid supplier request body */
        InvalidSupplierRequestProblem: {
            /** @example about:blank */
            type?: string;
            /** @example Invalid supplier request */
            title?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example One or more supplier fields are invalid */
            detail?: string;
            /** @example /api/suppliers */
            instance?: string;
            /** @description Validation messages grouped by JSON field; absent for malformed JSON */
            errors?: {
                [key: string]: string[];
            };
        };
        /** @description Problem Details response when a supplier does not exist */
        SupplierNotFoundProblem: {
            /** @example about:blank */
            type?: string;
            /** @example Supplier not found */
            title?: string;
            /**
             * Format: int32
             * @example 404
             */
            status?: number;
            /** @example Supplier with ID ca9bd61f-93da-4500-9e9d-48de1bea52fa was not found */
            detail?: string;
            /** @example /api/suppliers/ca9bd61f-93da-4500-9e9d-48de1bea52fa */
            instance?: string;
            /**
             * Format: uuid
             * @example ca9bd61f-93da-4500-9e9d-48de1bea52fa
             */
            supplierId?: string;
        };
        /** @description Problem Details response when the requested version is stale */
        SupplierUpdateConflictProblem: {
            /** @example about:blank */
            type?: string;
            /** @example Supplier update conflict */
            title?: string;
            /**
             * Format: int32
             * @example 409
             */
            status?: number;
            /** @example Supplier has changed since the requested version */
            detail?: string;
            /** @example /api/suppliers/ca9bd61f-93da-4500-9e9d-48de1bea52fa */
            instance?: string;
            /**
             * Format: uuid
             * @example ca9bd61f-93da-4500-9e9d-48de1bea52fa
             */
            supplierId?: string;
            /**
             * Format: int64
             * @example 0
             */
            requestedVersion?: number;
            /**
             * Format: int64
             * @example 1
             */
            currentVersion?: number | null;
        };
        /** @description Problem Details response when a valid bearer token is absent */
        UnauthorizedProblem: {
            /** @example about:blank */
            type?: string;
            /** @example Unauthorized */
            title?: string;
            /**
             * Format: int32
             * @example 401
             */
            status?: number;
            /** @example A valid bearer token is required */
            detail?: string;
            /** @example /api/admin/suppliers */
            instance?: string;
        };
        /** @description Problem Details response when the authenticated user is not an administrator */
        ForbiddenProblem: {
            /** @example about:blank */
            type?: string;
            /** @example Forbidden */
            title?: string;
            /**
             * Format: int32
             * @example 403
             */
            status?: number;
            /** @example Administrator access is required */
            detail?: string;
            /** @example /api/admin/suppliers */
            instance?: string;
        };
        /** @description Details used to create a supplier */
        CreateSupplierRequest: {
            /**
             * @description Supplier display name
             * @example New Campus Cafe
             */
            name: string;
            /**
             * @description Supplier category
             * @example Food/Coffee
             */
            type: string;
            /**
             * @description Campus building
             * @example COM3
             */
            building: string;
            /**
             * @description Floor label
             * @example 1
             */
            floor?: string | null;
            /**
             * @description Directions within or near the building
             * @example Beside the main entrance
             */
            locationDescription?: string | null;
            /**
             * Format: double
             * @description Latitude in decimal degrees
             * @example 1.2948
             */
            latitude: number;
            /**
             * Format: double
             * @description Longitude in decimal degrees
             * @example 103.7716
             */
            longitude: number;
            /**
             * Format: time
             * @description Local opening time; independent of closing time
             * @example 08:00
             */
            openingTime?: string | null;
            /**
             * Format: time
             * @description Local closing time; may be earlier for overnight operation
             * @example 18:00
             */
            closingTime?: string | null;
            /**
             * Format: uri
             * @description Absolute HTTP or HTTPS image URL
             * @example https://example.com/cafe.jpg
             */
            imageUrl?: string | null;
            /**
             * @description Initial status; defaults to ACTIVE when omitted
             * @default ACTIVE
             * @example ACTIVE
             * @enum {string|null}
             */
            status: "ACTIVE" | "INACTIVE" | null;
        };
        /** @description Status change guarded by the supplier's current version */
        ChangeSupplierStatusRequest: {
            /**
             * @description Desired supplier status
             * @example INACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * Format: int64
             * @description Version from the latest supplier response
             * @example 0
             */
            version: number;
        };
        /** @description Page of suppliers and pagination metadata */
        SupplierListResponse: {
            /** @description Suppliers in the requested page */
            items?: components["schemas"]["SupplierResponse"][];
            /**
             * Format: int32
             * @description Zero-based page number
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 20
             */
            size?: number;
            /**
             * Format: int64
             * @description Number of suppliers matching the query
             * @example 21
             */
            totalItems?: number;
            /**
             * Format: int32
             * @description Number of available pages
             * @example 2
             */
            totalPages?: number;
        };
        /** @description Supplier filter values for the endpoint's visibility scope */
        SupplierMetadataResponse: {
            /**
             * @description Distinct supplier categories sorted case-insensitively
             * @example [
             *       "Food",
             *       "Food/Coffee",
             *       "Printing",
             *       "Shopping"
             *     ]
             */
            types?: string[];
            /**
             * @description Distinct supplier buildings sorted case-insensitively
             * @example [
             *       "Blk AS8",
             *       "Central Library"
             *     ]
             */
            buildings?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Supplier UUID
                 * @example ca9bd61f-93da-4500-9e9d-48de1bea52fa
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supplier found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Malformed supplier UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRequestProblem"];
                };
            };
            /** @description Supplier not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SupplierNotFoundProblem"];
                };
            };
        };
    };
    updateSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Supplier UUID
                 * @example ca9bd61f-93da-4500-9e9d-48de1bea52fa
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSupplierRequest"];
            };
        };
        responses: {
            /** @description Supplier updated, or unchanged when the request is a no-op */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Malformed UUID or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRequestProblem"] | components["schemas"]["InvalidSupplierRequestProblem"];
                };
            };
            /** @description Bearer token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["UnauthorizedProblem"];
                };
            };
            /** @description Authenticated user is not an administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ForbiddenProblem"];
                };
            };
            /** @description Supplier not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SupplierNotFoundProblem"];
                };
            };
            /** @description Requested version is stale */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SupplierUpdateConflictProblem"];
                };
            };
        };
    };
    deleteSupplier: {
        parameters: {
            query: {
                /**
                 * @description Version from the latest supplier response
                 * @example 2
                 */
                version: number;
            };
            header?: never;
            path: {
                /**
                 * @description Supplier UUID
                 * @example ca9bd61f-93da-4500-9e9d-48de1bea52fa
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supplier permanently deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed UUID or missing, negative, decimal, or nonnumeric version */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRequestProblem"];
                };
            };
            /** @description Bearer token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["UnauthorizedProblem"];
                };
            };
            /** @description Authenticated user is not an administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ForbiddenProblem"];
                };
            };
            /** @description Supplier not found or already deleted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SupplierNotFoundProblem"];
                };
            };
            /** @description Requested version is stale */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SupplierUpdateConflictProblem"];
                };
            };
        };
    };
    listSuppliers: {
        parameters: {
            query?: {
                /**
                 * @description Case-insensitive partial match across name, building, and location description
                 * @example central
                 */
                search?: string;
                /**
                 * @description Case-insensitive exact supplier type
                 * @example Food
                 */
                type?: string;
                /**
                 * @description Case-insensitive exact building name
                 * @example Central Library
                 */
                building?: string;
                /**
                 * @description Zero-based page number
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Records per page
                 * @example 20
                 */
                size?: number;
                /**
                 * @description Sort as field,direction. Fields: name, type, building, openingTime, closingTime, createdAt, updatedAt. Directions: asc or desc.
                 * @example name,asc
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of matching active suppliers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierListResponse"];
                };
            };
            /** @description Invalid pagination or sort query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRequestProblem"];
                };
            };
        };
    };
    createSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupplierRequest"];
            };
        };
        responses: {
            /** @description Supplier created */
            201: {
                headers: {
                    /** @description Relative URL of the created supplier */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Missing, malformed, or invalid supplier fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidSupplierRequestProblem"];
                };
            };
            /** @description Bearer token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["UnauthorizedProblem"];
                };
            };
            /** @description Authenticated user is not an administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ForbiddenProblem"];
                };
            };
        };
    };
    changeSupplierStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Supplier UUID
                 * @example ca9bd61f-93da-4500-9e9d-48de1bea52fa
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSupplierStatusRequest"];
            };
        };
        responses: {
            /** @description Status changed, or unchanged when the request is a no-op */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Malformed UUID or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRequestProblem"] | components["schemas"]["InvalidSupplierRequestProblem"];
                };
            };
            /** @description Bearer token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["UnauthorizedProblem"];
                };
            };
            /** @description Authenticated user is not an administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ForbiddenProblem"];
                };
            };
            /** @description Supplier not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SupplierNotFoundProblem"];
                };
            };
            /** @description Requested version is stale */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SupplierUpdateConflictProblem"];
                };
            };
        };
    };
    getSupplierMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filter metadata for active suppliers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierMetadataResponse"];
                };
            };
        };
    };
    listSuppliersForAdmin: {
        parameters: {
            query?: {
                /**
                 * @description Case-insensitive partial match across name, building, and location description
                 * @example central
                 */
                search?: string;
                /**
                 * @description Case-insensitive exact supplier type
                 * @example Food
                 */
                type?: string;
                /**
                 * @description Case-insensitive exact building name
                 * @example Central Library
                 */
                building?: string;
                /**
                 * @description Optional supplier status. Omit to include every status.
                 * @example INACTIVE
                 */
                status?: "ACTIVE" | "INACTIVE";
                /**
                 * @description Zero-based page number
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Records per page
                 * @example 20
                 */
                size?: number;
                /**
                 * @description Sort as field,direction. Fields: name, type, building, openingTime, closingTime, createdAt, updatedAt, status. Directions: asc or desc.
                 * @example updatedAt,desc
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of matching suppliers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierListResponse"];
                };
            };
            /** @description Invalid status, pagination, or sort query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRequestProblem"];
                };
            };
            /** @description Bearer token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["UnauthorizedProblem"];
                };
            };
            /** @description Authenticated user is not an administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ForbiddenProblem"];
                };
            };
        };
    };
    getAdminSupplierMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filter metadata across all suppliers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierMetadataResponse"];
                };
            };
            /** @description Bearer token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["UnauthorizedProblem"];
                };
            };
            /** @description Authenticated user is not an administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ForbiddenProblem"];
                };
            };
        };
    };
}
