-- ============================================================
-- Order Service database
-- PostgreSQL
-- UUID values are generated by the Spring Boot application.
-- ============================================================

CREATE TABLE orders (
    id UUID PRIMARY KEY,

    requester_id UUID NOT NULL,
    courier_id UUID,

    title VARCHAR(120) NOT NULL,
    description VARCHAR(2000) NOT NULL,

    -- References to locations owned by Supplier Service.
    -- These are not PostgreSQL foreign keys because Supplier Service
    -- has a separate database.
    pickup_location_id UUID NOT NULL,
    dropoff_location_id UUID NOT NULL,

    -- Snapshots preserve the names shown when the order was created.
    -- Nullable at insert: order creation carries only location IDs, and the
    -- Supplier-owned names arrive asynchronously via an event, after which
    -- these columns are populated (see the Order Service README event flow).
    pickup_location_name_snapshot VARCHAR(160),
    dropoff_location_name_snapshot VARCHAR(160),

    credit_reward INTEGER NOT NULL,

    -- Used when an OPEN order requests a reward change.
    -- credit_reward remains unchanged until Credit Service confirms.
    pending_credit_reward INTEGER,

    -- Created and owned by Credit Service.
    credit_reservation_id UUID,

    pickup_deadline TIMESTAMPTZ NOT NULL,

    state VARCHAR(32) NOT NULL,

    -- Examples:
    -- REQUESTER_CANCELLED
    -- PICKUP_DEADLINE_PASSED
    -- COURIER_WITHDREW_AFTER_DEADLINE
    -- CREDIT_RESERVATION_REJECTED
    terminal_reason VARCHAR(64),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    state_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    accepted_at TIMESTAMPTZ,
    picked_up_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,

    -- Used by JPA @Version for optimistic locking.
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT chk_order_state CHECK (
        state IN (
            'PENDING_CREDIT',
            'OPEN',
            'ACCEPTED',
            'PICKED_UP',
            'DELIVERED',
            'COMPLETED',
            'CANCELLED',
            'EXPIRED',
            'RESERVATION_FAILED'
        )
    ),

    CONSTRAINT chk_title_not_blank CHECK (
        length(btrim(title)) BETWEEN 1 AND 120
    ),

    CONSTRAINT chk_description_not_blank CHECK (
        length(btrim(description)) BETWEEN 1 AND 2000
    ),

    CONSTRAINT chk_positive_reward CHECK (
        credit_reward > 0
    ),

    CONSTRAINT chk_positive_pending_reward CHECK (
        pending_credit_reward IS NULL OR pending_credit_reward > 0
    ),

    CONSTRAINT chk_different_locations CHECK (
        pickup_location_id <> dropoff_location_id
    ),

    CONSTRAINT chk_requester_not_courier CHECK (
        courier_id IS NULL OR requester_id <> courier_id
    ),

    CONSTRAINT chk_courier_assignment CHECK (
        (
            state IN ('ACCEPTED', 'PICKED_UP', 'DELIVERED', 'COMPLETED')
            AND courier_id IS NOT NULL
        )
        OR
        (
            state NOT IN ('ACCEPTED', 'PICKED_UP', 'DELIVERED', 'COMPLETED')
            AND courier_id IS NULL
        )
    ),

    CONSTRAINT chk_deadline_after_creation CHECK (
        pickup_deadline > created_at
    ),

    CONSTRAINT chk_updated_after_creation CHECK (
        updated_at >= created_at
    )
);

-- Available-order feed and expiry scheduler.
CREATE INDEX idx_orders_open_deadline
    ON orders (pickup_deadline, id)
    WHERE state = 'OPEN';

-- Sort open orders by highest reward.
CREATE INDEX idx_orders_open_reward
    ON orders (credit_reward DESC, id)
    WHERE state = 'OPEN';

-- Filter open orders by pickup location.
CREATE INDEX idx_orders_open_pickup_location
    ON orders (pickup_location_id, pickup_deadline)
    WHERE state = 'OPEN';

-- Filter open orders by drop-off location.
CREATE INDEX idx_orders_open_dropoff_location
    ON orders (dropoff_location_id, pickup_deadline)
    WHERE state = 'OPEN';

-- Requester history.
CREATE INDEX idx_orders_requester_history
    ON orders (requester_id, updated_at DESC);

-- Courier history.
CREATE INDEX idx_orders_courier_history
    ON orders (courier_id, updated_at DESC)
    WHERE courier_id IS NOT NULL;
