package com.friendoncampus.user.web;
import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import com.friendoncampus.user.service.*;
@RestControllerAdvice class RegistrationExceptionHandler {
 @ExceptionHandler({IllegalArgumentException.class,DuplicateRegistrationException.class}) ProblemDetail invalid(RuntimeException e){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST,e.getMessage()); p.setTitle("Invalid registration"); return p; }
 @ExceptionHandler(InvalidCredentialsException.class) ProblemDetail invalidCredentials(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.UNAUTHORIZED,"Incorrect email or password"); p.setTitle("Authentication failed"); return p; }
 @ExceptionHandler(EmailVerificationRequiredException.class) ProblemDetail emailVerificationRequired(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.FORBIDDEN,"Email verification is required before signing in"); p.setTitle("Email verification required"); p.setProperty("code", "EMAIL_VERIFICATION_REQUIRED"); return p; }
 @ExceptionHandler(InvalidPasswordResetCodeException.class) ProblemDetail invalidPasswordResetCode(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST,"Invalid or expired password reset code"); p.setTitle("Password reset failed"); return p; }
 @ExceptionHandler(InvalidEmailVerificationCodeException.class) ProblemDetail invalidEmailVerificationCode(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST,"Invalid or expired email verification code"); p.setTitle("Email verification failed"); return p; }
 @ExceptionHandler(EmailVerificationNotFoundException.class) ProblemDetail emailVerificationNotFound(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.NOT_FOUND,"No registered account was found for that email"); p.setTitle("Email verification unavailable"); return p; }
 @ExceptionHandler(EmailAlreadyVerifiedException.class) ProblemDetail emailAlreadyVerified(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"This email has already been verified"); p.setTitle("Email already verified"); return p; }
 @ExceptionHandler(EmailVerificationForbiddenException.class) ProblemDetail emailVerificationForbidden(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.FORBIDDEN,"This account cannot receive email verification"); p.setTitle("Email verification unavailable"); return p; }
 @ExceptionHandler(EmailVerificationDeliveryException.class) ProblemDetail emailVerificationDelivery(){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.SERVICE_UNAVAILABLE,"Unable to send the verification email. Please resend it later."); p.setTitle("Email delivery unavailable"); return p; }
 @ExceptionHandler(EmailVerificationCooldownException.class) ResponseEntity<ProblemDetail> emailVerificationCooldown(EmailVerificationCooldownException e){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.TOO_MANY_REQUESTS,"Please wait before requesting another verification email"); p.setTitle("Verification email sent recently"); return ResponseEntity.status(HttpStatus.TOO_MANY_REQUESTS).header(HttpHeaders.RETRY_AFTER,Long.toString(e.retryAfterSeconds())).body(p); }
 @ExceptionHandler(AdminAccessDeniedException.class) ProblemDetail adminAccessDenied(AdminAccessDeniedException e){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.FORBIDDEN,e.getMessage()); p.setTitle("Administrator access required"); return p; }
 @ExceptionHandler(AdminAccountNotFoundException.class) ProblemDetail adminAccountNotFound(AdminAccountNotFoundException e){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.NOT_FOUND,e.getMessage()); p.setTitle("Account not found"); return p; }
 @ExceptionHandler(AdminLifecycleException.class) ProblemDetail adminLifecycle(AdminLifecycleException e){ ProblemDetail p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,e.getMessage()); p.setTitle("Account change unavailable"); return p; }
}
